//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public int Id { get; set; }
        public string patente { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<int> monto_estacionamiento { get; set; }
        public string estado { get; set; }

        internal object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
